"""empty message

Revision ID: 7ab6a519de65
Revises: 
Create Date: 2020-04-23 09:11:03.417342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab6a519de65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('filedata',
    sa.Column('src_id', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.String(length=100), nullable=False),
    sa.Column('use_count', sa.String(length=100), nullable=False),
    sa.Column('file_md5', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('src_id')
    )
    op.create_table('share',
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('share_key', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('is_folder', sa.Boolean(), nullable=False),
    sa.Column('file_size', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('share_id')
    )
    op.create_table('upload',
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('forbidden', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('upload')
    op.drop_table('share')
    op.drop_table('filedata')
    op.drop_table('admin')
    # ### end Alembic commands ###
